openapi: 3.0.0
info:
  title: Hospital
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: Get/Create user(s)
      tags:
        - Users
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 10
                uniqueItems: false
                items:
                  $ref: '#/components/schemas/Person'
              examples:
                example-1: {}
      operationId: get/create-users
      description: 'GET, CREATE users'
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples: {}
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
    post:
      summary: ''
      operationId: post-users
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    minimum: 0
                    maximum: 100000
                    exclusiveMinimum: false
                    example: 1
                required:
                  - id
              examples: {}
        '400':
          description: Bad Request
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1: {}
      description: Create new user
      parameters:
        - schema:
            type: string
            minLength: 1
          in: query
          description: ''
          required: true
          name: name
        - schema:
            type: string
            minLength: 1
          in: query
          name: middleName
          required: true
        - schema:
            type: string
            minLength: 1
          in: query
          name: surname
          required: true
      tags:
        - Users
  '/therapy/disease/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: ''
    post:
      summary: Register disease
      operationId: post-users-disease-userId
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LifeEvent'
        '400':
          description: Bad Request
      parameters:
        - schema:
            type: string
            format: date
          in: query
          description: "Person's date of illness"
          name: startDate
          required: true
        - schema:
            type: string
            format: ''
          in: query
          name: name
          description: Name of illness
          required: true
        - schema:
            type: string
          in: query
          name: description
          description: Description of illness
          required: true
      description: ''
      tags:
        - Disease
  /therapy/prescription:
    parameters: []
    post:
      summary: Prescribe a treatment
      operationId: post-therapy-prescription-userId-diseaseId
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prescription'
      parameters:
        - schema:
            type: integer
            minLength: 1
            minimum: 0
            maximum: 100000
          in: query
          name: userId
          required: true
          description: id of user to get prescription
        - schema:
            type: integer
            minimum: 1
            maximum: 100000
          in: query
          name: diseaseId
          required: true
          description: 'id of disease, which user received after therapy'
  /therapy/medicalTest:
    post:
      summary: Prescribe a medical test
      operationId: post-therapy-medicalTest
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MedicalTest'
        '400':
          description: Bad Request
      description: ''
      parameters:
        - schema:
            type: integer
            minimum: 0
            maximum: 100000
          in: query
          name: userId
          description: id of user to get medical test
          required: true
        - schema:
            type: integer
            minimum: 0
            maximum: 100000
          in: query
          name: diseaseId
          description: "id of user's disease"
          required: true
    get:
      summary: ''
      operationId: get-therapy-medicalTest
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                maxItems: 7
                items:
                  $ref: '#/components/schemas/MedicalTest'
        '400':
          description: Bad Request
      parameters:
        - schema:
            type: integer
            format: date
          in: query
          name: year
          description: ''
          required: true
  '/therapy/prescription/{prescriptionId}/drugDosage':
    parameters:
      - schema:
          type: integer
          minimum: 0
          maximum: 100000
        name: prescriptionId
        in: path
        required: true
    put:
      summary: "Change drug dosage (400 doesn't work, don't know how to set body parameters as required)"
      operationId: put-therapy-prescription-prescriptionId-drugDosage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Drug'
              examples: {}
        '400':
          description: Bad Request
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Drug'
            examples: {}
        description: New drug dosage
  '/therapy/medicalTest/{medicalTestId}/attachment':
    parameters:
      - schema:
          type: integer
          minimum: 0
          maximum: 100000
        name: medicalTestId
        in: path
        required: true
    post:
      summary: Add attachment to the medical test
      operationId: post-therapy-medicalTest-medicalTestId-attachment
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attachment'
        '400':
          description: Bad Request
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Attachment'
        description: ''
  /therapy/prescription/medication:
    get:
      summary: Get all ongoing medications
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                maxItems: 10
                uniqueItems: false
                minItems: 0
                items:
                  $ref: '#/components/schemas/Medication'
        '400':
          description: Bad Request
      operationId: get-therapy-prescription-medication
      parameters:
        - schema:
            type: boolean
          in: query
          name: isDone
          description: ''
          required: true
    parameters: []
components:
  schemas:
    Person:
      title: Person
      type: object
      description: hospital client entity
      x-examples: {}
      x-tags:
        - Users
      properties:
        id:
          type: integer
          minimum: 1
          maximum: 100000
        fullName:
          type: object
          properties:
            name:
              type: string
            middleName:
              type: string
            surname:
              type: string
        lifeEvents:
          type: array
          maxItems: 5
          minItems: 0
          items:
            $ref: '#/components/schemas/LifeEvent'
    LifeEvent:
      title: LifeEvent
      type: object
      x-tags:
        - Disease
      description: ''
      properties:
        id:
          type: integer
          minimum: 0
          maximum: 100000
        description:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
    Prescription:
      title: Prescription
      type: object
      x-tags:
        - Prescription
      properties:
        id:
          type: integer
          minimum: 0
          maximum: 100000
        description:
          type: string
        name:
          type: string
        drugs:
          type: array
          items:
            $ref: '#/components/schemas/Drug'
      description: ''
    Medication:
      title: Medication
      type: object
      x-tags:
        - Prescription
      properties:
        id:
          type: integer
          minimum: 0
          maximum: 100000
        date:
          type: string
          format: date
        isDone:
          type: boolean
        notes:
          type: string
        MedicationRegimen:
          type: object
          properties:
            name:
              type: string
            code:
              type: string
    Drug:
      title: Drug
      type: object
      x-tags:
        - Prescription
      x-examples: {}
      properties:
        id:
          type: integer
          minimum: 0
          maximum: 100000
        description:
          type: string
        name:
          type: string
        quantity:
          type: integer
          minimum: 1
          maximum: 100
    MedicalTest:
      title: MedicalTest
      type: object
      x-tags:
        - MedicalTest
      description: ''
      properties:
        id:
          type: integer
          minimum: 0
          maximum: 100000
        name:
          type: string
        description:
          type: string
        date:
          type: string
          format: date
        attachment:
          $ref: '#/components/schemas/Attachment'
    Attachment:
      title: Attachment
      type: object
      x-tags:
        - MedicalTest
      description: ''
      properties:
        id:
          type: integer
          minimum: 0
          maximum: 100000
        Conent:
          type: string
        Description:
          type: string
        FileName:
          type: string
        Path:
          type: string
  securitySchemes: {}
