openapi: 3.0.0
info:
  title: Hospital
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-users
      description: ''
components:
  schemas:
    Person:
      title: Person
      type: object
      properties:
        id:
          type: integer
        fullName:
          type: object
          minProperties: 3
          maxProperties: 3
          properties:
            name:
              type: string
            middleName:
              type: string
            surname:
              type: string
        lifeEvent:
          type: object
          minProperties: 3
          maxProperties: 3
          properties:
            description:
              type: string
            startDate:
              type: string
            endDate:
              type: string
      description: hospital client entity
  securitySchemes: {}
